;;; custom.el --- custom config Emacs -*- lexical-binding: t -*-
;;
;;; Commentary:
;; Custom configuration generated by Emacs.  Manual edits are not
;; recommended.
;;
;;; Code:

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(casual-lib-use-unicode t)
 '(cider-download-java-sources t)
 '(column-number-mode t)
 '(custom-safe-themes
   '("b9c002dc827fb75b825da3311935c9f505d48d7ee48f470f0aa7ac5d2a595ab2"
     "d609d9aaf89d935677b04d34e4449ba3f8bbfdcaaeeaab3d21ee035f43321ff1"
     "59c36051a521e3ea68dc530ded1c7be169cd19e8873b7994bfc02a216041bf3b"
     "00d7122017db83578ef6fba39c131efdcb59910f0fac0defbe726da8072a0729"
     "90185f1d8362727f2aeac7a3d67d3aec789f55c10bb47dada4eefb2e14aa5d01"
     default))
 '(global-display-line-numbers-mode t)
 '(inhibit-startup-screen t)
 '(package-selected-packages
   '(casual cider clojure-ts-mode crux debbugs delight diff-hl
	    dired-preview dired-subtree editorconfig ef-themes eglot
	    elfeed elisp-def elisp-demos ellama embark-consult eros
	    exec-path-from-shell expand-region faceup helpful
	    highlight-defined jarchive keycast keyfreq lingva
	    live-py-mode lorem-ipsum magit marginalia markdown-mode
	    nerd-icons-completion nerd-icons-dired nerd-icons-ibuffer
	    org package-lint-flymake pdf-tools pulsar
	    rainbow-delimiters smartparens suggest trashed undo-tree
	    verilog-mode wgrep which-key window-tool-bar
	    yasnippet-snippets))
 '(tab-bar-mode t)
 '(tool-bar-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Source Code Pro" :foundry "ADBO" :slant normal :weight regular :height 128 :width normal)))))


;;; custom.el ends here
